-- Gerado a partir do schema-export.json; revisar antes de executar no Supabase.
-- IDs foram mantidos como text para preservar compatibilidade com o SQL Server legado.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "brincadeiras" (
  "id" varchar(36) NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(500),
  "rules" text,
  "type" varchar(20) DEFAULT 'team',
  "duration" integer DEFAULT 30,
  "status" varchar(20) DEFAULT 'active',
  "default_points" integer DEFAULT 10,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36),
  "game_type" varchar(50) DEFAULT 'standard',
  "checkpoints" text,
  "evento_id" text
);

CREATE TABLE IF NOT EXISTS "caca_tesouro_partidas" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "brincadeira_id" varchar(36) NOT NULL,
  "status" varchar(20) NOT NULL,
  "round_number" integer NOT NULL,
  "target_checkpoint_id" varchar(36),
  "completed_checkpoint_ids" text,
  "started_at" timestamptz NOT NULL,
  "round_started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "starting_team_id" varchar(36),
  "turn_team_id" varchar(36),
  "turn_available_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "caca_tesouro_scans" (
  "id" varchar(36) NOT NULL,
  "partida_id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "brincadeira_id" varchar(36) NOT NULL,
  "round_number" integer NOT NULL,
  "checkpoint_id" varchar(36) NOT NULL,
  "crianca_id" varchar(36) NOT NULL,
  "time_id" varchar(36) NOT NULL,
  "uid" varchar(100) NOT NULL,
  "scanned_at" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "caca_tesouro_tempos" (
  "id" varchar(36) NOT NULL,
  "partida_id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "time_id" varchar(36) NOT NULL,
  "started_at" timestamptz,
  "completed_at" timestamptz,
  "elapsed_ms" bigint
);

CREATE TABLE IF NOT EXISTS "checkpoint_tags" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkpoint_id" varchar(36) NOT NULL,
  "tag_uid" varchar(50) NOT NULL,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "checkpoints" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "name" varchar(100) NOT NULL,
  "type" varchar(20) DEFAULT 'NFC',
  "checkpoint_purpose" varchar(20) DEFAULT 'game',
  "ip" varchar(15),
  "zone" varchar(100),
  "map_x" integer,
  "map_y" integer,
  "led_color" varchar(20) DEFAULT '#00FF00',
  "points" integer DEFAULT 10,
  "status" varchar(20) DEFAULT 'offline',
  "territory_owner_time_id" varchar(36),
  "territory_locked_until" timestamptz,
  "territory_cooldown_until" timestamptz,
  "last_conquered_at" timestamptz,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36),
  "authorized_tags" text,
  "last_seen" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "clientes" (
  "id" varchar(36) NOT NULL,
  "name" varchar(100) NOT NULL,
  "city" varchar(100),
  "state" varchar(2),
  "email" varchar(100) NOT NULL,
  "phone" varchar(20),
  "plano" varchar(20) DEFAULT 'starter',
  "status" varchar(20) DEFAULT 'active',
  "events_done" integer DEFAULT 0,
  "last_access" timestamptz,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "conquistas" (
  "id" varchar(36) NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(500),
  "icon" varchar(50),
  "color" varchar(20),
  "required_type" varchar(50),
  "required_value" integer,
  "points_bonus" integer DEFAULT 0,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "crianca_conquistas" (
  "crianca_id" varchar(36) NOT NULL,
  "conquista_id" varchar(36) NOT NULL,
  "unlocked_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "criancas" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "time_id" varchar(36),
  "name" varchar(100) NOT NULL,
  "nickname" varchar(100),
  "age" integer,
  "avatar" varchar(64) DEFAULT '??',
  "bracelet_code" varchar(50),
  "scores" integer DEFAULT 0,
  "status" varchar(20) DEFAULT 'active',
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36)
);

CREATE TABLE IF NOT EXISTS "empresas" (
  "id" varchar(36) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "cidade" varchar(100),
  "estado" varchar(2),
  "telefone" varchar(20),
  "plano" varchar(50) DEFAULT 'starter',
  "status" varchar(50) DEFAULT 'active',
  "data_criacao" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "data_atualizacao" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "evento_brincadeiras" (
  "evento_id" varchar(36) NOT NULL,
  "brincadeira_id" varchar(36) NOT NULL,
  "ordem" integer DEFAULT 0,
  "points_multiplier" integer DEFAULT 1,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "support_tickets" (
  "id" varchar(36) PRIMARY KEY,
  "empresa_id" varchar(36),
  "client" varchar(255) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'aberto',
  "priority" varchar(20) NOT NULL DEFAULT 'media',
  "description" text,
  "assignee" varchar(255),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "eventos" (
  "id" varchar(36) NOT NULL,
  "cliente_id" varchar(36),
  "name" varchar(100) NOT NULL,
  "description" varchar(500),
  "date" date NOT NULL,
  "time" time,
  "duration" integer DEFAULT 120,
  "status" varchar(20) DEFAULT 'scheduled',
  "enable_display" integer DEFAULT 1,
  "enable_location" integer DEFAULT 0,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36),
  "active_game_type" varchar(50) DEFAULT 'none',
  "active_brincadeira_id" varchar(36),
  "floor_plan_data" text,
  "floor_plan_name" varchar(255),
  "floor_plan_type" varchar(100)
);

CREATE TABLE IF NOT EXISTS "leituras" (
  "id" varchar(36) NOT NULL,
  "checkpoint_id" varchar(36) NOT NULL,
  "crianca_id" varchar(36),
  "uid" varchar(50) NOT NULL,
  "brincadeira_id" text,
  "authorized" integer DEFAULT 0,
  "points_awarded" integer DEFAULT 0,
  "signal_strength" integer,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36)
);

CREATE TABLE IF NOT EXISTS "logins" (
  "id" varchar(36) NOT NULL,
  "empresa_id" varchar(36) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "status" varchar(50) DEFAULT 'active',
  "ultimo_acesso" timestamptz,
  "data_criacao" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "role" varchar(50) DEFAULT 'admin',
  "family_name" varchar(255)
);

CREATE TABLE IF NOT EXISTS "family_invites" (
  "id" varchar(36) PRIMARY KEY,
  "empresa_id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "crianca_id" varchar(36),
  "email" varchar(255),
  "token_hash" varchar(128) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "expires_at" timestamptz NOT NULL,
  "used_at" timestamptz,
  "created_by" varchar(36),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "family_child_links" (
  "id" varchar(36) PRIMARY KEY,
  "login_id" varchar(36) NOT NULL,
  "crianca_id" varchar(36) NOT NULL,
  "empresa_id" varchar(36) NOT NULL,
  "relationship" varchar(50) NOT NULL DEFAULT 'responsável',
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "approved_by" varchar(36),
  "approved_at" timestamptz,
  "rejected_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_family_invites_token_hash" ON "family_invites" ("token_hash");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_family_child_link" ON "family_child_links" ("login_id", "crianca_id");

CREATE TABLE IF NOT EXISTS "logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tipo" varchar(20) NOT NULL,
  "cliente_id" varchar(36),
  "evento_id" varchar(36),
  "message" varchar(500) NOT NULL,
  "details" text,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36)
);

CREATE TABLE IF NOT EXISTS "mensagens_display" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "text" varchar(500) NOT NULL,
  "type" varchar(20) DEFAULT 'custom',
  "sender" varchar(100),
  "sent_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "pontuacoes" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "crianca_id" varchar(36) NOT NULL,
  "brincadeira_id" text,
  "checkpoint_id" varchar(36) NOT NULL,
  "points" integer NOT NULL,
  "leitura_id" varchar(36),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36)
);

CREATE TABLE IF NOT EXISTS "pulseiras" (
  "code" varchar(50) NOT NULL,
  "status" varchar(20) DEFAULT 'disponivel',
  "crianca_id" varchar(36),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36)
);

CREATE TABLE IF NOT EXISTS "settings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "setting_key" varchar(100) NOT NULL,
  "setting_value" text,
  "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "staff" (
  "id" varchar(36) NOT NULL,
  "name" varchar(100) NOT NULL,
  "role" varchar(50) NOT NULL,
  "login" varchar(100) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "status" varchar(20) DEFAULT 'offline',
  "last_access" timestamptz,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "times" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36),
  "name" varchar(50) NOT NULL,
  "color" varchar(20) NOT NULL,
  "points" integer DEFAULT 0,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "empresa_id" varchar(36)
);

CREATE TABLE IF NOT EXISTS "zonas" (
  "id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "name" varchar(100) NOT NULL,
  "color" varchar(20) NOT NULL,
  "x" integer NOT NULL,
  "y" integer NOT NULL,
  "width" integer NOT NULL,
  "height" integer NOT NULL,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- Colunas exigidas pelas rotas atuais do backend Node.
ALTER TABLE "logins" ADD COLUMN IF NOT EXISTS "family_name" varchar(255);
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "empresa_id" text;
ALTER TABLE "checkpoints" ADD COLUMN IF NOT EXISTS "location" varchar(100);
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "latitude" double precision;
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "longitude" double precision;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__brincade__3213E83FA8E61AF2') THEN
  ALTER TABLE "brincadeiras" ADD CONSTRAINT "PK__brincade__3213E83FA8E61AF2" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__caca_tes__3213E83F8450C49A') THEN
  ALTER TABLE "caca_tesouro_partidas" ADD CONSTRAINT "PK__caca_tes__3213E83F8450C49A" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__caca_tes__3213E83F600198BE') THEN
  ALTER TABLE "caca_tesouro_scans" ADD CONSTRAINT "PK__caca_tes__3213E83F600198BE" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__caca_tes__3213E83F976260F2') THEN
  ALTER TABLE "caca_tesouro_tempos" ADD CONSTRAINT "PK__caca_tes__3213E83F976260F2" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__checkpoi__3213E83FB8065A13') THEN
  ALTER TABLE "checkpoint_tags" ADD CONSTRAINT "PK__checkpoi__3213E83FB8065A13" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__checkpoi__3213E83FB6D1708F') THEN
  ALTER TABLE "checkpoints" ADD CONSTRAINT "PK__checkpoi__3213E83FB6D1708F" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__clientes__3213E83F6BF1E412') THEN
  ALTER TABLE "clientes" ADD CONSTRAINT "PK__clientes__3213E83F6BF1E412" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__conquist__3213E83F4F0D26FA') THEN
  ALTER TABLE "conquistas" ADD CONSTRAINT "PK__conquist__3213E83F4F0D26FA" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__crianca___213C2CFF26481BB9') THEN
  ALTER TABLE "crianca_conquistas" ADD CONSTRAINT "PK__crianca___213C2CFF26481BB9" PRIMARY KEY ("crianca_id", "conquista_id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__criancas__3213E83F76B74F48') THEN
  ALTER TABLE "criancas" ADD CONSTRAINT "PK__criancas__3213E83F76B74F48" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__empresas__3213E83FC96C8FA1') THEN
  ALTER TABLE "empresas" ADD CONSTRAINT "PK__empresas__3213E83FC96C8FA1" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__evento_b__C4A104BA0DD4DCE7') THEN
  ALTER TABLE "evento_brincadeiras" ADD CONSTRAINT "PK__evento_b__C4A104BA0DD4DCE7" PRIMARY KEY ("evento_id", "brincadeira_id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__eventos__3213E83FBD04E5E4') THEN
  ALTER TABLE "eventos" ADD CONSTRAINT "PK__eventos__3213E83FBD04E5E4" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__leituras__3213E83F5D36D3D4') THEN
  ALTER TABLE "leituras" ADD CONSTRAINT "PK__leituras__3213E83F5D36D3D4" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__logins__3213E83F57818161') THEN
  ALTER TABLE "logins" ADD CONSTRAINT "PK__logins__3213E83F57818161" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__logs__3213E83FFD30ACAA') THEN
  ALTER TABLE "logs" ADD CONSTRAINT "PK__logs__3213E83FFD30ACAA" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__mensagen__3213E83F95810D6B') THEN
  ALTER TABLE "mensagens_display" ADD CONSTRAINT "PK__mensagen__3213E83F95810D6B" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__pontuaco__3213E83FE7FD06CA') THEN
  ALTER TABLE "pontuacoes" ADD CONSTRAINT "PK__pontuaco__3213E83FE7FD06CA" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__pulseira__357D4CF8CB99523E') THEN
  ALTER TABLE "pulseiras" ADD CONSTRAINT "PK__pulseira__357D4CF8CB99523E" PRIMARY KEY ("code");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__settings__3213E83F4D79CD35') THEN
  ALTER TABLE "settings" ADD CONSTRAINT "PK__settings__3213E83F4D79CD35" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__staff__3213E83F80857AE0') THEN
  ALTER TABLE "staff" ADD CONSTRAINT "PK__staff__3213E83F80857AE0" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__times__3213E83FE6C742EE') THEN
  ALTER TABLE "times" ADD CONSTRAINT "PK__times__3213E83FE6C742EE" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK__zonas__3213E83F534C9F84') THEN
  ALTER TABLE "zonas" ADD CONSTRAINT "PK__zonas__3213E83F534C9F84" PRIMARY KEY ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UQ_caca_tesouro_scan_crianca') THEN
  ALTER TABLE "caca_tesouro_scans" ADD CONSTRAINT "UQ_caca_tesouro_scan_crianca" UNIQUE ("partida_id", "round_number", "crianca_id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UQ_caca_tesouro_tempo_equipe') THEN
  ALTER TABLE "caca_tesouro_tempos" ADD CONSTRAINT "UQ_caca_tesouro_tempo_equipe" UNIQUE ("partida_id", "time_id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UQ_checkpoint_tag') THEN
  ALTER TABLE "checkpoint_tags" ADD CONSTRAINT "UQ_checkpoint_tag" UNIQUE ("checkpoint_id", "tag_uid");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UQ__logins__AB6E61641C935B6A') THEN
  ALTER TABLE "logins" ADD CONSTRAINT "UQ__logins__AB6E61641C935B6A" UNIQUE ("email");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UQ__settings__0DFAC427D445889B') THEN
  ALTER TABLE "settings" ADD CONSTRAINT "UQ__settings__0DFAC427D445889B" UNIQUE ("setting_key");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UQ__staff__7838F27224FF163E') THEN
  ALTER TABLE "staff" ADD CONSTRAINT "UQ__staff__7838F27224FF163E" UNIQUE ("login");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_brincadeiras_empresas') THEN
  ALTER TABLE "brincadeiras" ADD CONSTRAINT "FK_brincadeiras_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__checkpoin__check__01142BA1') THEN
  ALTER TABLE "checkpoint_tags" ADD CONSTRAINT "FK__checkpoin__check__01142BA1" FOREIGN KEY ("checkpoint_id") REFERENCES "checkpoints" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__checkpoin__event__7B5B524B') THEN
  ALTER TABLE "checkpoints" ADD CONSTRAINT "FK__checkpoin__event__7B5B524B" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__checkpoin__terri__7C4F7684') THEN
  ALTER TABLE "checkpoints" ADD CONSTRAINT "FK__checkpoin__terri__7C4F7684" FOREIGN KEY ("territory_owner_time_id") REFERENCES "times" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_checkpoints_empresas') THEN
  ALTER TABLE "checkpoints" ADD CONSTRAINT "FK_checkpoints_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__crianca_c__conqu__17F790F9') THEN
  ALTER TABLE "crianca_conquistas" ADD CONSTRAINT "FK__crianca_c__conqu__17F790F9" FOREIGN KEY ("conquista_id") REFERENCES "conquistas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__crianca_c__crian__17036CC0') THEN
  ALTER TABLE "crianca_conquistas" ADD CONSTRAINT "FK__crianca_c__crian__17036CC0" FOREIGN KEY ("crianca_id") REFERENCES "criancas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__criancas__evento__6E01572D') THEN
  ALTER TABLE "criancas" ADD CONSTRAINT "FK__criancas__evento__6E01572D" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__criancas__time_i__6EF57B66') THEN
  ALTER TABLE "criancas" ADD CONSTRAINT "FK__criancas__time_i__6EF57B66" FOREIGN KEY ("time_id") REFERENCES "times" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_criancas_empresas') THEN
  ALTER TABLE "criancas" ADD CONSTRAINT "FK_criancas_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__evento_br__brinc__619B8048') THEN
  ALTER TABLE "evento_brincadeiras" ADD CONSTRAINT "FK__evento_br__brinc__619B8048" FOREIGN KEY ("brincadeira_id") REFERENCES "brincadeiras" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__evento_br__event__60A75C0F') THEN
  ALTER TABLE "evento_brincadeiras" ADD CONSTRAINT "FK__evento_br__event__60A75C0F" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__eventos__cliente__5441852A') THEN
  ALTER TABLE "eventos" ADD CONSTRAINT "FK__eventos__cliente__5441852A" FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_eventos_empresas') THEN
  ALTER TABLE "eventos" ADD CONSTRAINT "FK_eventos_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__leituras__checkp__06CD04F7') THEN
  ALTER TABLE "leituras" ADD CONSTRAINT "FK__leituras__checkp__06CD04F7" FOREIGN KEY ("checkpoint_id") REFERENCES "checkpoints" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__leituras__crianc__07C12930') THEN
  ALTER TABLE "leituras" ADD CONSTRAINT "FK__leituras__crianc__07C12930" FOREIGN KEY ("crianca_id") REFERENCES "criancas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_leituras_empresas') THEN
  ALTER TABLE "leituras" ADD CONSTRAINT "FK_leituras_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__logins__empresa___6BE40491') THEN
  ALTER TABLE "logins" ADD CONSTRAINT "FK__logins__empresa___6BE40491" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__logs__cliente_id__208CD6FA') THEN
  ALTER TABLE "logs" ADD CONSTRAINT "FK__logs__cliente_id__208CD6FA" FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__logs__evento_id__2180FB33') THEN
  ALTER TABLE "logs" ADD CONSTRAINT "FK__logs__evento_id__2180FB33" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__mensagens__event__1CBC4616') THEN
  ALTER TABLE "mensagens_display" ADD CONSTRAINT "FK__mensagens__event__1CBC4616" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__pontuacoe__check__0F624AF8') THEN
  ALTER TABLE "pontuacoes" ADD CONSTRAINT "FK__pontuacoe__check__0F624AF8" FOREIGN KEY ("checkpoint_id") REFERENCES "checkpoints" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__pontuacoe__crian__0D7A0286') THEN
  ALTER TABLE "pontuacoes" ADD CONSTRAINT "FK__pontuacoe__crian__0D7A0286" FOREIGN KEY ("crianca_id") REFERENCES "criancas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__pontuacoe__event__0C85DE4D') THEN
  ALTER TABLE "pontuacoes" ADD CONSTRAINT "FK__pontuacoe__event__0C85DE4D" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_pontuacoes_empresas') THEN
  ALTER TABLE "pontuacoes" ADD CONSTRAINT "FK_pontuacoes_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__pulseiras__crian__73BA3083') THEN
  ALTER TABLE "pulseiras" ADD CONSTRAINT "FK__pulseiras__crian__73BA3083" FOREIGN KEY ("crianca_id") REFERENCES "criancas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_pulseiras_empresas') THEN
  ALTER TABLE "pulseiras" ADD CONSTRAINT "FK_pulseiras_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__times__evento_id__66603565') THEN
  ALTER TABLE "times" ADD CONSTRAINT "FK__times__evento_id__66603565" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_times_empresas') THEN
  ALTER TABLE "times" ADD CONSTRAINT "FK_times_empresas" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id");
END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK__zonas__evento_id__25518C17') THEN
  ALTER TABLE "zonas" ADD CONSTRAINT "FK__zonas__evento_id__25518C17" FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
END IF; END $$;


-- Estado persistido por evento. O endpoint do checkpoint usa este estado
-- após reinicialização do backend, sem depender de variáveis globais.
CREATE TABLE IF NOT EXISTS "event_game_state" (
  "evento_id" varchar(36) PRIMARY KEY,
  "empresa_id" varchar(36) NOT NULL,
  "mode" varchar(20) NOT NULL DEFAULT 'idle',
  "game_type" varchar(50) NOT NULL DEFAULT 'none',
  "game_id" varchar(36),
  "game_name" varchar(255),
  "started_at" timestamptz,
  "stopped_at" timestamptz,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_event_game_state_empresa"
  ON "event_game_state" ("empresa_id");


CREATE TABLE IF NOT EXISTS "monster_hunt_partidas" (
  "id" varchar(36) PRIMARY KEY,
  "empresa_id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "brincadeira_id" varchar(36),
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "hp" integer NOT NULL DEFAULT 500,
  "max_hp" integer NOT NULL DEFAULT 500,
  "normal_damage" integer NOT NULL DEFAULT 10,
  "special_checkpoint_damage" integer NOT NULL DEFAULT 30,
  "special_attack_damage" integer NOT NULL DEFAULT 50,
  "special_checkpoint_id" varchar(36),
  "winner_time_id" varchar(36),
  "version" integer NOT NULL DEFAULT 0,
  "started_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "monster_hunt_team_states" (
  "id" varchar(36) PRIMARY KEY,
  "partida_id" varchar(36) NOT NULL,
  "empresa_id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "time_id" varchar(36) NOT NULL,
  "hp" integer NOT NULL DEFAULT 500,
  "max_hp" integer NOT NULL DEFAULT 500,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "version" integer NOT NULL DEFAULT 0,
  "defeated_at" timestamptz,
  "victory_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_monster_hunt_team_state"
  ON "monster_hunt_team_states" ("partida_id", "time_id");
CREATE INDEX IF NOT EXISTS "idx_monster_hunt_team_states_evento"
  ON "monster_hunt_team_states" ("empresa_id", "evento_id", "partida_id");

CREATE TABLE IF NOT EXISTS "monster_hunt_scans" (
  "id" varchar(36) PRIMARY KEY,
  "partida_id" varchar(36) NOT NULL,
  "empresa_id" varchar(36) NOT NULL,
  "evento_id" varchar(36) NOT NULL,
  "brincadeira_id" varchar(36),
  "checkpoint_id" varchar(36) NOT NULL,
  "crianca_id" varchar(36) NOT NULL,
  "time_id" varchar(36),
  "uid" varchar(255),
  "leitura_id" varchar(36),
  "attack_type" varchar(30) NOT NULL,
  "damage" integer NOT NULL DEFAULT 0,
  "monster_hp_after" integer NOT NULL,
  "monster_defeated" boolean NOT NULL DEFAULT false,
  "version" integer NOT NULL DEFAULT 0,
  "scanned_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_monster_hunt_scans_checkpoint"
  ON "monster_hunt_scans" ("partida_id", "checkpoint_id", "scanned_at");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_monster_hunt_scan_reading"
  ON "monster_hunt_scans" ("leitura_id") WHERE "leitura_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_monster_hunt_partidas_evento"
  ON "monster_hunt_partidas" ("empresa_id", "evento_id", "status");
CREATE INDEX IF NOT EXISTS "idx_monster_hunt_scans_evento"
  ON "monster_hunt_scans" ("empresa_id", "evento_id", "partida_id");